id = "encore-zed"
name = "Encore"
version = "0.0.9"
schema_version = 1
authors = ["Maksim Shushkevich <m.e.shushkevich@yandex.com>"]
description = "Encore extension for Zed"
repository = "https://github.com/encore-ecosystem/encore-zed"
languages = ["languages/encore"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.encore]
repository = "https://github.com/encore-ecosystem/tree-sitter-encore"
commit = "914146b68bf7477edcf950deec1e8eca41be9af1"

[language_servers.encore-lsp]
name = "Encore LSP"
languages = ["Encore"]

[language_servers.encore-lsp.language_ids]
Encore = "encore"
